### ISSUE TITLE
Fix the installer package path

### ISSUE THREAD

**Issue by geforce-hisa0904** [MicrosoftDocs/visualstudio-docs.ja-jp#1784]
Regarding the 1 of section of "To add an installer package by using Package.xml", I guess that the path of installer package is wrong at least when using Visual Studio 2017 and Microsoft Visual Studio Installer Projects.
Could you confirm it?

**Current:**
32 bit system : C:\Program Files\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages
64 bit system : C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages

>1. In File Explorer, open the Packages folder.
>By default, the path is C:\Program Files\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages on a 32-bit system and C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages on a 64-bit system.

**Suggestion:**
32 bit system : C:\Program Files\Microsoft SDKs\ClickOnce Bootstrapper\Packages
64 bit system : C:\Program Files (x86)\Microsoft SDKs\ClickOnce Bootstrapper\Packages

[フィードバックをこちらに入力してください]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 73a13e0d-b415-6953-0a25-bbfd3f6a3724
* Version Independent ID: d422e2a7-5595-9274-ace8-38a91fcef21a
* Content: [方法: ClickOnce アプリケーションと共に必須コンポーネントを含める - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/deployment/how-to-include-prerequisites-with-a-clickonce-application?view=vs-2017#feedback)
* Content Source: [docs/deployment/how-to-include-prerequisites-with-a-clickonce-application.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/deployment/how-to-include-prerequisites-with-a-clickonce-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #2968](https://github.com/MicrosoftDocs/visualstudio-docs/issues/2968) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @geforce-hisa0904 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/2968

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
