### ISSUE TITLE
SafeNativeMethods 例のコード

### ISSUE THREAD

**Issue by KOZ60** [MicrosoftDocs/visualstudio-docs.ja-jp#1808]
SafeNativeMethods 例のコードが UnsafeNativeMethods の例になってしまってます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f4a45470-c7dc-059e-eb84-43cc4b5af148
* Version Independent ID: 4071c652-e8ed-a180-5039-8c7d3890abd7
* Content: [CA1060:P/Invoke を NativeMethods クラスに移動します - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/code-quality/ca1060-move-p-invokes-to-nativemethods-class?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1060-move-p-invokes-to-nativemethods-class.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/code-quality/ca1060-move-p-invokes-to-nativemethods-class.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
Hello, @KOZ60 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KOZ60

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/visualstudio/code-quality/ca1060-move-p-invokes-to-nativemethods-class?view=vs-2019#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
