### ISSUE TITLE
一貫性のない注釈

### ISSUE THREAD

**Issue by inouaTI** [MicrosoftDocs/visualstudio-docs.ja-jp#1818]
「関数に対する一貫性のない注釈」とは何かわからない。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 119d2a58-bc57-cc6d-ed73-80828a0816a7
* Version Independent ID: 0b1da5bb-f8ca-0d00-930c-9cd212438a2d
* Content: [C28251 - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/code-quality/c28251?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DJA-JP%26k%3Dk(C28251)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=vs-2019)
* Content Source: [docs/code-quality/c28251.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/code-quality/c28251.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @inouaTI
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@inouaTI
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
