### ISSUE TITLE
メニュー バーの [テスト] の枝に [実行] はありません

### ISSUE THREAD

**Issue by wraith13** [MicrosoftDocs/visualstudio-docs.ja-jp#1828]
https://docs.microsoft.com/ja-jp/visualstudio/get-started/tutorial-projects-solutions?view=vs-2019#next-steps
```md
メニュー バーから **[テスト]**  >  **[実行]**  >  **[すべてのテスト]** を選択します。
```

となっていますが、 Mirosoft Visual Studio Community 2019 Version 16.2.2 日本語版で確認した所、メニュー バーの **[テスト]** には **[ウィンドウ]** しか存在しませんでした。 ( 同機能そのものは テスト エクスプローラー から問題無く利用できてるように見えます。 )

![image](https://user-images.githubusercontent.com/645907/63291864-5f21a400-c2ff-11e9-9733-9729ae46b7f1.png)

**Comment by srvbpigh** [comment]
Hello, @wraith13
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #3799](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3799) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@wraith13
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら https://github.com/MicrosoftDocs/visualstudio-docs/issues/3799 を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
