### ISSUE TITLE
markdown から HTML のレンダリングが正常に行われていないように見えます

### ISSUE THREAD

**Issue by wraith13** [MicrosoftDocs/visualstudio-docs.ja-jp#1830]
https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/install/install-visual-studio-versions-side-by-side.md
こちらを見る分には

```
Visual Studio 2015 で作成されたソリューションを Visual Studio 2017 を使用して開く場合、Visual Studio 2017 に固有の機能が実装されていない限り、後で以前のバージョンのソリューションを開き、再度変更することができます。
```

となっているのですが、実際のページでは

https://docs.microsoft.com/ja-jp/visualstudio/install/install-visual-studio-versions-side-by-side?view=vs-2019

```
Visual Studio 2017 で作成されたソリューションを Visual Studio 2019 を使用して開く場合、Visual Studio 2019 に固有の機能が実装されていない限り、後で以前のバージョンのソリューションを開き、再度変更することが。
```

のように何故か末尾の ```できます``` が欠けています。

**Comment by srvbpigh** [comment]
Hello, @wraith13
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by wraith13** [comment]
そこのドロップダウンを 2019 にしてる時のレンダリング結果がおかしいです。

![image](https://user-images.githubusercontent.com/645907/63732341-c5ce3100-c8ae-11e9-9f8e-ba2a8ba22af5.png)

あ、分かりました！　moniker ディレクティブの挙動を全く理解していませんでした。

![image](https://user-images.githubusercontent.com/645907/63732522-b0a5d200-c8af-11e9-8030-422ae74b7c1b.png)

おかしいのはこの下側のソースですね。こちらを修正するプルリクを投げて起きます！
