### ISSUE TITLE
[Visual Studio での C++ の概要]が最初しか VS 2019 ベースでの記述になっていません

### ISSUE THREAD

**Issue by wraith13** [MicrosoftDocs/visualstudio-docs.ja-jp#1845]
https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/ide/getting-started-with-cpp-in-visual-studio.md
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/getting-started-with-cpp-in-visual-studio.md

このページの説明がオリジナルの英語版も含めて、最初は VS 2019 対応の記述になっているのですが、`コンソール アプリ プロジェクトを作成するには` / `To create a console app project` 以降については VS 2017 のままになってしまっています。

**Comment by srvbpigh** [comment]
Hello, @wraith13
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@wraith13
フィードバックをお送りいただきありがとうございました。
この問題はこれに関連しているようです：https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1830
ライブページでも複製されるかどうかを確認してください：https://docs.microsoft.com/ja-jp/visualstudio/ide/getting-started-with-cpp-in-visual-studio?view=vs-2019

敬具
Microsoft DOCS International Team

**Comment by wraith13** [comment]
日本語版
https://docs.microsoft.com/ja-jp/visualstudio/ide/getting-started-with-cpp-in-visual-studio?view=vs-2019
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/645907/64532252-184a2b80-d34c-11e9-98ea-5b543a51eb3f.png">
英語版
https://docs.microsoft.com/en-us/visualstudio/ide/getting-started-with-cpp-in-visual-studio?view=vs-2019
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/645907/64532419-68c18900-d34c-11e9-95f3-5538467647e3.png">

このようにライブページでも再現しています。 #1830 とは違い、 moniker ディレクティブの問題などではなく、単純に VS 2019 対応の作業が途中までしか行われていないように見えます。

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #3941](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3941) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@wraith13
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (XXX) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
