### ISSUE TITLE
Button_Clickイベントが効かない

### ISSUE THREAD

**Issue by showery-hwang** [MicrosoftDocs/visualstudio-docs.ja-jp#1853]
チュートリアル通りに作ってみましたが、「Display」ボタンをクリックしてもなにも表示しない。デバッグでみると、Button_Clickメソッドに入っていないようです。何かが悪いでしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 329e32a3-766c-1739-022b-5d1a8bc6f4aa
* Version Independent ID: d74a678c-d9b5-90c4-cd63-8451fefaa887
* Content: [C# で WPF を使った Hello World アプリ - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/get-started/csharp/tutorial-wpf?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/get-started/csharp/tutorial-wpf.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @showery-hwang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by showery-hwang** [comment]
I add Click property to Button tag as follow, so it worked.
Click="Button_Click"

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4019](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4019) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
こんにちは、@<共同作成者の GITHUB 名> 
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/visualstudio-docs/issues/4019) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
