### ISSUE TITLE
説明不足！！

### ISSUE THREAD

**Issue by DoNgocLinh2010** [MicrosoftDocs/visualstudio-docs.ja-jp#1856]
手順5-7 から手順5-8まで、どうやってログインできますか？
手順を書いてください。
システムにログインできないと、手順５－８を読んでも理解できないです！

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4286e07a-6d43-8800-fd06-be7f8ad21d20
* Version Independent ID: e6b188d8-adc0-cb16-cffa-63bfe2d3ecd4
* Content: [Visual Studio での Django 学習チュートリアル、手順 5、認証](https://docs.microsoft.com/ja-jp/visualstudio/python/learn-django-in-visual-studio-step-05-django-authentication?view=vs-2019#feedback)
* Content Source: [docs/python/learn-django-in-visual-studio-step-05-django-authentication.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/python/learn-django-in-visual-studio-step-05-django-authentication.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @DoNgocLinh2010
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4090](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4090) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lichasu** [comment]
こんにちは、@DoNgocLinh2010
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/visualstudio-docs/issues/4090) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
