### ISSUE TITLE
superfastcode2(C++)が参照設定してもpythonへimportできない（pybind11）

### ISSUE THREAD

**Issue by hamukawa0406** [MicrosoftDocs/visualstudio-docs.ja-jp#1862]
visual studio 2019
windows 10
以上の環境でこのページを行ったところ、c++のファイルのビルドはうまくいったが、
pythonからDLLを呼び出そうとしても、
"  unresolved import 'superfastcode2' "
とエラーが起きる。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Python 用の C++ 拡張機能の記述 - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @hamukawa0406
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #4257](https://github.com/MicrosoftDocs/visualstudio-docs/issues/4257) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@hamukawa0406
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/visualstudio-docs/issues/4257) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
