### ISSUE TITLE
[なし]ではなく[None]ではないか

### ISSUE THREAD

**Issue by currysita** [MicrosoftDocs/visualstudio-docs.ja-jp#1867]
誤:
なし
ビルド プロセスでは使用しないことが推奨されるファイルを表します。

正:
None
ビルド プロセスでは使用しないことが推奨されるファイルを表します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 97e663f7-3bac-61af-28bb-f0e471dcdca6
* Version Independent ID: 97985f56-e0ac-a03d-f651-b86cc2b85804
* Content: [MSBuild プロジェクトの共通項目 - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#none)
* Content Source: [docs/msbuild/common-msbuild-project-items.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/msbuild/common-msbuild-project-items.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by srvbpigh** [comment]
Hello, @currysita
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@currysita   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#none   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
