### ISSUE TITLE
TextBlockコントロール追加時のマークアップについて

### ISSUE THREAD

**Issue by cailte** [MicrosoftDocs/visualstudio-docs.ja-jp#1869]
「TextBlockコントロールを追加する」の項で、説明の通りTextBlockコントロールをデザイナに追加したが、XAMLマークアップが例と異なる。
こちらの環境ではTextBlockタグに x:Name="textBlock" が存在している。

また、これに関連することと推測するが、追加したTextBlockコントロールを削除し、再度TextBlockコントロールを追加すると
"エラー	XDG0062	このスコープで重複する名前 'textBlock' を登録することはできません。"
というエラーが出る。削除したにもかかわらず名称重複と言われてしまい、どこを修正すれば解消するのか解らない。
再追加したコントロールのx:Nameを変更すればエラーは消えるが、根本的な解決になっていない。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 329e32a3-766c-1739-022b-5d1a8bc6f4aa
* Version Independent ID: d74a678c-d9b5-90c4-cd63-8451fefaa887
* Content: [C# で WPF を使った Hello World アプリ - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/get-started/csharp/tutorial-wpf?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/get-started/csharp/tutorial-wpf.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @cailte
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by cailte** [comment]
＞削除したにもかかわらず名称重複と言われてしまい、どこを修正すれば解消するのか解らない。
これについて、Visual Studio 2019の挙動に問題があるようです。
デザイナにコントロールを追加した時点でメモリにコントロール情報が追加され、それはコントロールを削除しても消えません。
xamlファイルを閉じることでメモリが開放されます。
コントロールを削除してもxamlファイルを閉じるまでは重複エラーが表示されてしまうようです。

**Comment by srvbpigh** [comment]
こんにちは、@cailte  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/visualstudio-docs/issues/4566) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@cailte -- thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the Report a Problem tool (https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) to report the issue. When you do so, your report becomes part of the work items that are listed in the in the Visual Studio Developer Community (https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
#please-translate

**Comment by srvbpigh** [comment]
上記のコメントからの翻訳 

@cailte -- フィードバックをお送りいただき誠にありがとうございました。こちらが正しい場所にログインしたかどうかを確認するには、問題を報告するための問題報告ツール（https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio）をご利用ください。それにより、お客様から寄せられた報告は、Visual Studio 開発者コミュニティー（https://developercommunity.visualstudio.com/）の作業アイテムリストに載せられ、エンジニアがその問題の改善に取り組む際に、お客様にはエンジニアチームと直接かかわっていただくことができます。
