### ISSUE TITLE
"証明書フォルダ－" on localized document

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs.ja-jp#39]
@mutsun commented on [Fri Apr 28 2017](https://github.com/MicrosoftDocs/visualstudio-docs/issues/102)

"証明書フォルダー” should be "certificates フォルダー" because this word identify the folder which contain certificate files that are downloading to local folder when user creates offline-installation image with "--layout" option. 

https://docs.microsoft.com/ja-jp/visualstudio/install/create-an-offline-installation-of-visual-studio 

1.証明書をインストールします (これらはレイアウト フォルダーの証明書フォルダーにあります。 インストールするには、それぞれを単に右クリックします)。

Expected:
1.証明書をインストールします (これらはレイアウト フォルダーの certificates フォルダーにあります。 インストールするには、それぞれを単に右クリックします)。

---

@ghogen commented on [Thu Sep 21 2017](https://github.com/MicrosoftDocs/visualstudio-docs/issues/102#issuecomment-331250151)

@nokura Nobuko, can you check this?

---

@gewarren commented on [Thu Oct 19 2017](https://github.com/MicrosoftDocs/visualstudio-docs/issues/102#issuecomment-338013888)

@mutsun thank you for reporting this, and sorry for the delay. Hopefully our localization team can look at this soon.

---

@gewarren commented on [Mon Jun 11 2018](https://github.com/MicrosoftDocs/visualstudio-docs/issues/102#issuecomment-396326120)

@nokura or @CeciAc could one of you take a look at this? Should it be moved to the Japanese repo's issues page?

**Comment by gewarren** [comment]
@CeciAc Thank you!

**Comment by CeciAc** [comment]
Hi @mutsun
We check this with our linguist and we couldn't find the reported sentence in the actual live page.
The error must have been fixed after the page was updated.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team
