### ISSUE TITLE
Visual Studio 2017 Version 15.8.1で利用できる ptvsdバージョンについて

### ISSUE THREAD

**Issue by bardno1** [MicrosoftDocs/visualstudio-docs.ja-jp#65]
Python ツール/ptvsd のバージョンを「4.1.1a9」にしろと怒られます。
大事な内容なので記載をお願いします

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 904b359d-de5e-adf4-9966-e1ab5be204be
* Version Independent ID: 564c35dd-ac25-8db4-ea48-e76476c50f89
* Content: [リモート Linux コンピューターでの Python コードのデバッグ](https://docs.microsoft.com/ja-jp/visualstudio/python/debugging-python-code-on-remote-linux-machines)
* Content Source: [docs/python/debugging-python-code-on-remote-linux-machines.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/python/debugging-python-code-on-remote-linux-machines.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #1419](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1419) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@bardno1

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。
 
そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら   (https://github.com/MicrosoftDocs/visualstudio-docs/issues/1419) を確認してください。

記事の品質向上にご協力いただき誠にありがとうございました。

敬具
Microsoft DOCS International   Team
