### ISSUE TITLE
Wrong translation.

### ISSUE THREAD

**Issue by whenimg0ne** [MicrosoftDocs/visualstudio-docs.ja-jp#77]
`手順 1. Hyper-V を無効にする` should be `手順 1. Hyper-V を有効にする` .   `Hyper-V を無効にする` means "Disable Hyper-V" which is completely opposite from "Enable Hyper-V".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Visual Studio Build Tools をコンテナーにインストールする - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/install/build-tools-container?view=vs-2017#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/install/build-tools-container.md)
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by CeciAc** [comment]
こんにちは、@whenimg0ne

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@whenimg0ne

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/visualstudio/install/build-tools-container?view=vs-2017#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  


敬具  
Microsoft DOCS International Team
