### ISSUE TITLE
There is no image on the Japanese site.

### ISSUE THREAD

**Issue by changeworld** [MicrosoftDocs/visualstudio-docs.ja-jp#813]
[フィードバックをこちらに入力してください]
The English site has images.
However, there is no image on the Japanese site.
en:
<img width="661" alt="2019-02-11 17 14 22" src="https://user-images.githubusercontent.com/1207985/52551625-a561ec00-2e20-11e9-877f-24f8266f62b9.png">

ja:
<img width="666" alt="2019-02-11 17 14 16" src="https://user-images.githubusercontent.com/1207985/52551623-a266fb80-2e20-11e9-874f-d3af2ff87fbf.png">

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e5bd3466-656f-7af2-46aa-c7aa9392c41f
* Version Independent ID: 240ea484-05b2-76a2-27dd-5e09d1a86c43
* Content: [コードのスタイル設定 - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/ide/code-styles-and-quick-actions?view=vs-2017)
* Content Source: [docs/ide/code-styles-and-quick-actions.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/ide/code-styles-and-quick-actions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
Hello, @changeworld 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @changeworld

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/visualstudio/ide/code-styles-and-quick-actions?view=vs-2017

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
